"""Read vulnerability summaries generated by the audit workflow."""

from __future__ import annotations

import json
from pathlib import Path
from typing import cast

from .config import CONFIG
from .database import normalize_identifier
from .schema import JsonObject, RowDict, row_str


def vulnerability_json_path(identifier: str) -> Path:
    return CONFIG.audit_dir / f"{identifier}-000" / "overall.json"


def read_vulnerabilities(session: RowDict) -> JsonObject:
    identifier = normalize_identifier(row_str(session, "identifier"))
    path = vulnerability_json_path(identifier)
    if not path.exists():
        raise FileNotFoundError(f"未找到 {path}")
    payload = cast(JsonObject, json.loads(path.read_text(encoding="utf-8")))
    findings = payload.get("findings")
    if not isinstance(findings, list):
        raise ValueError(f"{path} 中缺少 findings 数组")
    return {
        "ok": True,
        "path": str(path),
        "generated_at": payload.get("generated_at"),
        "identifier": str(payload.get("identifier", identifier)),
        "count": payload.get("count", len(findings)),
        "findings": findings,
    }


def unavailable_payload(session: RowDict, error: str) -> JsonObject:
    identifier = row_str(session, "identifier")
    return {
        "ok": True,
        "available": False,
        "error": error,
        "requested_update": False,
        "path": str(vulnerability_json_path(identifier)),
        "identifier": identifier,
        "count": 0,
        "findings": [],
    }
